# Kubernetes ConfigMaps for MerajutASA.id
# Application configuration and environment settings

apiVersion: v1
kind: ConfigMap
metadata:
  name: merajutasa-config
  labels:
    app: merajutasa
    component: configuration
data:
  # Application Configuration
  log_level: "info"
  node_env: "production"
  
  # Redis Configuration
  redis_host: "redis-cluster"
  redis_port: "6379"
  
  # Monitoring Configuration
  metrics_interval: "30"
  health_check_timeout: "10"
  
  # Backup Configuration
  backup_schedule: "0 2 * * *"  # Daily at 2 AM
  backup_retention_days: "30"
  
  # Rate Limiting Configuration
  rate_limit_window: "60"
  rate_limit_max_requests: "100"
  
  # Security Configuration
  session_timeout: "3600"
  max_request_size: "10485760"  # 10MB
  
  # Performance Configuration
  worker_processes: "auto"
  connection_timeout: "30"
  keepalive_timeout: "65"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-schemas
  labels:
    app: merajutasa-collector
    component: event-schemas
data:
  public-event-v1.json: |
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": ["event_name", "occurred_at", "received_at"],
      "properties": {
        "event_name": {
          "type": "string",
          "enum": ["pub_hero_view", "pub_feedback_submit", "pub_navigation", "pub_interaction"]
        },
        "occurred_at": {
          "type": "string",
          "format": "date-time"
        },
        "received_at": {
          "type": "string",
          "format": "date-time"
        },
        "meta": {
          "type": "object",
          "properties": {
            "path": {"type": "string"},
            "user_agent": {"type": "string"},
            "ip_address": {"type": "string"},
            "session_id": {"type": "string"}
          }
        }
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx-proxy
    component: reverse-proxy
data:
  nginx.conf: |
    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
        
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript;
        
        upstream signer_backend {
            least_conn;
            server merajutasa-signer:4601 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream chain_backend {
            least_conn;
            server merajutasa-chain:4602 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream collector_backend {
            least_conn;
            server merajutasa-collector:4603 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        server {
            listen 80;
            
            location /api/signer/ {
                proxy_pass http://signer_backend/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/chain/ {
                proxy_pass http://chain_backend/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/collector/ {
                proxy_pass http://collector_backend/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /health {
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'merajutasa-signer'
      static_configs:
      - targets: ['merajutasa-signer:4601']
      metrics_path: /metrics
      scrape_interval: 30s
    
    - job_name: 'merajutasa-chain'
      static_configs:
      - targets: ['merajutasa-chain:4602']
      metrics_path: /metrics
      scrape_interval: 30s
    
    - job_name: 'merajutasa-collector'
      static_configs:
      - targets: ['merajutasa-collector:4603']
      metrics_path: /metrics
      scrape_interval: 15s
    
    - job_name: 'merajutasa-monitoring'
      static_configs:
      - targets: ['merajutasa-monitoring:4604']
      metrics_path: /metrics
      scrape_interval: 30s