# Opsi B: Berlaku jika GitHub App "Settings" (Probot) terpasang pada repo ini.
# Standarisasi proteksi branch dan perilaku repo (non-negotiable).

repository:
  has_issues: true
  has_projects: true
  has_wiki: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  private: false
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "ci/build"
          - "ci/lint"
          - "ci/test"
          - "security/codeql"
          - "security/secret-scan"
      enforce_admins: true
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

  - name: "release/*"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "ci/build"
          - "ci/lint"
          - "ci/test"
          - "security/codeql"
          - "security/secret-scan"
      enforce_admins: true
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true