blank_issues_enabled: false
contact_links:
  - name: Governance & Integrity guide
    url: https://xcodeprem.github.io/merajutasa.id/
    about: Read repo governance and integrity documentation before filing issues.