name: Copilot Auto Review and Merge

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
  workflow_dispatch: {}

concurrency:
  group: copilot-auto-merge-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  review-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Read config
        id: cfg
        run: |
          echo "ASSIGNEE=$(jq -r '.assignee' .github/copilot-orchestrator.json)" >> $GITHUB_OUTPUT
          echo "LABEL_INPROG=$(jq -r '.labels.inProgress' .github/copilot-orchestrator.json)" >> $GITHUB_OUTPUT
          echo "LABEL_DONE=$(jq -r '.labels.done' .github/copilot-orchestrator.json)" >> $GITHUB_OUTPUT

      - name: Identify linked issue
        id: link
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Prefer explicit closing keywords
          echo "$PR_BODY" | tr '\r' '\n' | \
            sed -nE 's/.*((close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)[[:space:]]+#([0-9]+)).*/\3/ip' | head -n1 > issue.txt
          if [ ! -s issue.txt ]; then
            # Fallback: first #number anywhere
            echo "$PR_BODY" | sed -nE 's/.*#([0-9]+).*/\1/p' | head -n1 > issue.txt || true
          fi
          ISSUE=$(cat issue.txt || true)
          echo "Linked issue: ${ISSUE:-<none>}"
          echo "ISSUE=$ISSUE" >> $GITHUB_OUTPUT

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review "${{ github.event.pull_request.number }}" --approve

      - name: Squash merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --squash --auto --delete-branch || gh pr merge "${{ github.event.pull_request.number }}" --squash --admin --delete-branch

    - name: Mark linked issue done
        if: ${{ steps.link.outputs.ISSUE != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          n='${{ steps.link.outputs.ISSUE }}'
      gh label create '${{ steps.cfg.outputs.LABEL_DONE }}' --color 2ea043 --description "Completed by Copilot" 2>/dev/null || true
          gh issue edit "$n" --remove-label '${{ steps.cfg.outputs.LABEL_INPROG }}' --add-label '${{ steps.cfg.outputs.LABEL_DONE }}' --state closed
      gh issue comment "$n" --body "Automated merge completed; marking done."

      - name: Trigger next assignment
        if: ${{ steps.link.outputs.ISSUE != '' }}
        uses: benc-uk/workflow-dispatch@25938ad20bcf54d63616cf6d7d0a3f114c0b0e4d
        with:
          workflow: Copilot Sub-issue Assigner
          ref: ${{ github.ref_name }}
