name: Dependency Graph
on:
  pull_request:
    paths:
      - "scripts/deps/**"
      - "config/**"
      - "docs/architecture/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "package-lock.json"
      - "yarn.lock"
  push:
    
    param($m)
    $inside = $m.Groups[1].Value + 'main' + $m.Groups[2].Value
    if ($inside -notmatch 'master') { return 'branches: [' + ($inside.Trim().TrimEnd(',')) + ', master]' }
    return $m.Value
  
permissions:
  contents: read
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "24"
          cache: 'npm'
      - run: npm ci
      - run: npm run deps:graph
      - run: npm run deps:check
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: always()
        with:
          name: dependency-graph
          path: |
            build/deps/graph.json
            docs/architecture/dependency-graph.mmd