name: Integrated Infrastructure Health
on:
  pull_request:
    paths:
      - "tools/integrated-health-check.js"
      - "infrastructure/**"
      - "package.json"
      - ".github/workflows/integrated-health.yml"
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  infra-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "24"
          cache: 'npm'
      - run: npm ci
      - name: Run unified health check
        run: npm run health:check
      - name: Upload health report
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: integrated-health-report
          path: artifacts/integrated-health-check-report.json