name: Mirror main to master

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to master
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B master
          git merge --no-edit --ff-only origin/main || true
          git push origin master