name: Mirror main to master

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  mirror:
    name: Mirror main → master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push HEAD (main) to master
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push --force-with-lease origin HEAD:refs/heads/master