name: npm audit (advisory)

on:
  schedule:
    - cron: '20 17 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: npm-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '24'
      - run: npm ci
      - run: npm audit --audit-level=high
