name: orphanage-content-validation

on:
  pull_request:
    paths:
      - 'content/orphanages/**'
      - '.github/workflows/orphanage-content-validation.yml'

jobs:
    validate:
        name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portal
        uses: actions/checkout@v4
        with:
          path: portal

      - name: Checkout governance
        uses: actions/checkout@v4
        with:
          repository: xcodeprem/merajutasa-governance
          path: governance

      - name: Validate orphanage content
        uses: ./governance/.github/actions/validate-orphanages
        with:
          content_dir: portal/content/orphanages