name: "OSV Scanner"
on:
  pull_request:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: read
jobs:
  osv:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install osv-scanner
        run: |
          curl -sSfL https://raw.githubusercontent.com/google/osv-scanner/main/install.sh | sh -s -- -b /usr/local/bin
      - run: osv-scanner -r . --skip-git -o osv-results.json || true
      - name: Enforce OSV policy
        run: |
          node tools/enforce-osv.js
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: osv-results
          path: |
            osv-results.json
            artifacts/sca-osv-enforce-summary.json