name: Deploy Pages (Dashboard Snapshots)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * *' # nightly publish with fresh snapshots
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Run A8 (no-silent-drift) Gates
        uses: ./.github/actions/run-a8
        with:
          policy-path: 'tools/policy/policy.json'
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
      - name: Generate latest snapshots (H1)
        run: |
          node tools/fairness/generate-equity-snapshots.js || true
          node tools/derive-under-served-list.js || true
          node tools/equity-anomaly-detector.js || true
          node tools/weekly-trend-aggregator.js || true
          node tools/generate-h1-kpi-summary.js || true
          node tools/monthly-feedback-rollup.js || true
          node tools/changelog-excerpt-generate.js || true
          node tools/risk-digest.js || true
      - name: Prepare static snapshot
        run: |
          mkdir -p dist
          cp -r public/equity-ui/* dist/
          # publish latest KPI/weekly/anomalies if present
          mkdir -p dist/data
          [ -f artifacts/h1-kpi-summary.json ] && cp artifacts/h1-kpi-summary.json dist/data/ || true
          [ -f artifacts/weekly-trends.json ] && cp artifacts/weekly-trends.json dist/data/ || true
          [ -f artifacts/equity-anomalies.json ] && cp artifacts/equity-anomalies.json dist/data/ || true
          [ -f artifacts/under-served.json ] && cp artifacts/under-served.json dist/data/ || true
          [ -f artifacts/feedback-monthly-rollup.json ] && cp artifacts/feedback-monthly-rollup.json dist/data/ || true
          [ -f artifacts/changelog-excerpt.json ] && cp artifacts/changelog-excerpt.json dist/data/ || true
          [ -f artifacts/risk-digest.json ] && cp artifacts/risk-digest.json dist/data/ || true
          # placeholder revocations snapshot
          echo "[]" > dist/data/revocations.json
          # rewrite UI to load /data/*.json if available
          echo "" > dist/.nojekyll
          # generate minimal changelog page if draft exists
          if [ -f artifacts/changelog-excerpt-draft.md ]; then \
            printf '<!doctype html><html><head><meta charset="utf-8"><title>Changelog</title></head><body><pre>' > dist/changelog.html; \
            sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' artifacts/changelog-excerpt-draft.md >> dist/changelog.html; \
            printf '</pre></body></html>' >> dist/changelog.html; \
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
