name: PR Label Recommendations

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: pr-labeler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  recommend-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
      - run: npm ci
      - name: Generate recommendations
        run: node tools/pr-label-advisor.js
      - name: Upload recommendations
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: pr-label-recommendations
          path: artifacts/pr-label-recommendations.json
