name: Project Sync (labels -> board)

on:
  workflow_dispatch:
    inputs:
      numbers:
        description: Comma-separated issue numbers to sync
        required: false
        default: "98"

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '24'
      - name: Sync items
        env:
          # Prefer classic PAT to ensure Projects write permissions
          GH_PROJECT_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_OWNER: Andhika-Rey
          PROJECT_TITLE: MerajutASA Roadmap
          GITHUB_REPOSITORY: ${{ github.repository }}
          INPUT_NUMBERS: ${{ inputs.numbers }}
        run: |
          npm ci --ignore-scripts
          npm run project:sync
      - name: Re-run Spot-Check
        uses: benc-uk/workflow-dispatch@25938ad20bcf54d63616cf6d7d0a3f114c0b0e4d # v1
        with:
          workflow: Project Spot-Check
          token: ${{ github.token }}
