name: Project Sync (labels -> board)

on:
  workflow_dispatch:
    inputs:
      numbers:
        description: Comma-separated issue numbers to sync
        required: false
        default: "98"

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Sync items
        env:
          # Prefer classic PAT to ensure Projects write permissions
          GH_PROJECT_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_OWNER: Andhika-Rey
          PROJECT_TITLE: MerajutASA Roadmap
          GITHUB_REPOSITORY: ${{ github.repository }}
          INPUT_NUMBERS: ${{ inputs.numbers }}
        run: |
          npm ci --ignore-scripts
          npm run project:sync
      - name: Re-run Spot-Check
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Project Spot-Check
          token: ${{ github.token }}
