name: "SBOM (Syft)"
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  sbom:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: sbom-${{ github.run_id }}
          path: sbom.spdx.json
          retention-days: 90