name: Security & Integrity Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  verify:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Governance verify
        run: npm run governance:verify

      - name: Spec hash verify
        run: npm run spec-hash:verify

      - name: Param integrity
        run: npm run param:integrity

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-integrity-artifacts
          path: |
            artifacts/**/*.json
            artifacts/**/*.md
          if-no-files-found: warn