name: Security & Integrity Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  verify:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Governance verify
        run: npm run governance:verify
        continue-on-error: true

      - name: Spec hash verify
        run: npm run spec-hash:verify
        continue-on-error: true

      - name: Param integrity
        run: npm run param:integrity
        continue-on-error: true

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: security-integrity-artifacts
          path: |
            artifacts/**/*.json
            artifacts/**/*.md
          if-no-files-found: warn