name: Seed Labels (Project v2)

on:
  workflow_dispatch: {}

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Create/update labels
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }} # Classic PAT
        with:
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          script: |
            const owner = process.env.GITHUB_REPOSITORY.split('/')[0];
            const repo = process.env.GITHUB_REPOSITORY.split('/')[1];

            const labels = [
              // Priority Labels - Aligned with Infrastructure Update Analysis
              { name: 'P0', color: 'b60205', description: '🚨 URGENT - Complete within 7 days' },
              { name: 'P1', color: 'd93f0b', description: '⚡ HIGH PRIORITY - Complete within 30 days' },
              { name: 'P2', color: 'fbca04', description: '📋 MEDIUM PRIORITY - Complete within 90 days' },
              { name: 'P3', color: '0e8a16', description: '🔄 PLANNED - Next 6 months' },
              { name: 'urgent', color: 'b60205', description: 'Alias to P0' },
              { name: 'high-priority', color: 'd93f0b', description: 'Alias to P1' },
              { name: 'medium', color: 'fbca04', description: 'Alias to P2' },
              { name: 'planned', color: '0e8a16', description: 'Alias to P3' },

              // 15 Infrastructure Domains - From Lead Infrastructure Architect Summary
              { name: 'area:security-layer', color: '5319e7', description: 'Security hardening, auth, rate limiting (3 components)' },
              { name: 'area:monitoring-observability', color: '1d76db', description: 'Metrics, tracing, alerting (8 components)' },
              { name: 'area:performance-optimization', color: '0e8a16', description: 'Caching, compression, monitoring (7 components)' },
              { name: 'area:high-availability', color: 'c2e0c6', description: 'Auto-scaling, disaster recovery (6 components)' },
              { name: 'area:compliance-governance', color: 'd93f0b', description: 'Audit, privacy, automation (4 components)' },
              { name: 'area:api-gateway-services', color: '0052cc', description: 'Orchestration, mesh, docs (4 components)' },
              { name: 'area:cicd-pipeline', color: 'fbca04', description: 'Automated deployment (1 component)' },
              { name: 'area:container-orchestration', color: 'c2e0c6', description: 'Docker and Kubernetes infrastructure' },
              { name: 'area:data-management', color: '1d76db', description: 'Backup and storage systems' },
              { name: 'area:integration-platform', color: 'e99695', description: 'Platform, analyzer (2 components)' },
              { name: 'area:ai-ml-integration', color: '0e8a16', description: 'Anomaly detection, analytics, decision support' },
              { name: 'area:executive-dashboard', color: 'fbca04', description: 'KPI visualization, reporting engine' },
              { name: 'area:infrastructure-modernization', color: 'c2e0c6', description: 'Component upgrades, optimization' },
              { name: 'area:developer-experience', color: 'd93f0b', description: 'Tools, documentation, automation' },
              { name: 'area:advanced-enterprise', color: '5319e7', description: 'Federation, zero-trust, localization' },

              // Legacy area labels for backward compatibility
              { name: 'area:security', color: '5319e7' },
              { name: 'area:compliance', color: '1d76db' },
              { name: 'area:observability', color: '0052cc' },
              { name: 'area:performance', color: '0e8a16' },
              { name: 'area:high-availability', color: 'c2e0c6' },
              { name: 'area:api-gateway', color: 'bfdadc' },
              { name: 'area:equity-ui', color: 'fef2c0' },
              { name: 'area:docs', color: 'c5def5' },
              { name: 'area:ci-cd', color: 'e99695' },
              { name: 'area:configuration', color: 'c2e0c6' },
              { name: 'area:logging', color: 'c5def5' },
              { name: 'area:error-handling', color: 'c5def5' },
              { name: 'area:testing', color: 'fbca04' },
              { name: 'area:backup', color: 'c2e0c6' },
              { name: 'area:load-testing', color: 'fbca04' },
              { name: 'area:security-audit', color: '5319e7' },
              { name: 'area:data-pipeline', color: '0052cc' },
              { name: 'area:mobile-api', color: 'bfdadc' },
              { name: 'area:integration', color: 'c5def5' },

              // Enhanced Phase Labels - Detailed Implementation Status
              { name: 'phase:1', color: '0e8a16', description: 'Foundation - Security, Observability, Backup (100%)' },
              { name: 'phase:2-week-1', color: '1d76db', description: 'Docker & Kubernetes (87/100 - 71.3KB)' },
              { name: 'phase:2-week-2', color: '1d76db', description: 'Performance optimization (75/100 - 89.2KB)' },
              { name: 'phase:2-week-3', color: '0e8a16', description: 'Advanced monitoring (100/100 - 91.1KB)' },
              { name: 'phase:2-week-4', color: '0e8a16', description: 'API Gateway & Management (100/100 - 94.5KB)' },
              { name: 'phase:2-week-5', color: 'fbca04', description: 'High Availability & Resilience (77/100 - 139.7KB)' },
              { name: 'phase:2-week-6', color: 'd93f0b', description: 'Compliance & Security Enhancement (67/100 - 145.5KB)' },
              { name: 'phase:2-week-7', color: 'ededed', description: 'AI/ML Integration & Advanced Analytics (Planned - 120-140KB)' },
              { name: 'phase:2-week-8', color: 'ededed', description: 'Executive Dashboard & Advanced Reporting (Planned - 150-170KB)' },
              { name: 'phase:3-q1', color: 'ededed', description: 'Advanced Enterprise Features - Federation, Zero Trust, Localization' },
              { name: 'phase:3-q2', color: 'ededed', description: 'AI-Driven Governance - Intelligent Automation, Fairness AI, NLP' },
              { name: 'phase:3-q3', color: 'ededed', description: 'Ecosystem Expansion - External Integration, Analytics, Community' },
              { name: 'phase:3-q4', color: 'ededed', description: 'Next-Gen Platform - Quantum Security, Edge Computing, Emerging Tech' },
              { name: 'phase:infrastructure-modernization', color: '5319e7', description: 'Component upgrades and optimization' },
              { name: 'phase:developer-experience', color: 'd93f0b', description: 'Tools, documentation, automation improvements' },

              // Component-Specific Labels - 37 Infrastructure Components
              { name: 'component:security-hardening', color: '5319e7', description: 'Enhanced security measures and threat detection' },
              { name: 'component:authentication', color: '5319e7', description: 'User authentication and authorization' },
              { name: 'component:rate-limiting', color: '5319e7', description: 'API rate limiting and throttling' },
              { name: 'component:metrics-collection', color: '1d76db', description: 'System metrics and performance monitoring' },
              { name: 'component:distributed-tracing', color: '1d76db', description: 'Request tracing across services' },
              { name: 'component:alerting-system', color: '1d76db', description: 'Alert management and notification' },
              { name: 'component:log-aggregation', color: '1d76db', description: 'Centralized log collection and analysis' },
              { name: 'component:health-monitoring', color: '1d76db', description: 'Component health and status monitoring' },
              { name: 'component:anomaly-detection', color: '1d76db', description: 'AI-powered anomaly detection' },
              { name: 'component:performance-dashboards', color: '1d76db', description: 'Real-time performance visualization' },
              { name: 'component:error-tracking', color: '1d76db', description: 'Error collection and analysis' },
              { name: 'component:caching-layer', color: '0e8a16', description: 'Multi-level caching strategy' },
              { name: 'component:content-compression', color: '0e8a16', description: 'Response compression optimization' },
              { name: 'component:database-optimization', color: '0e8a16', description: 'Query and index optimization' },
              { name: 'component:load-balancing', color: '0e8a16', description: 'Traffic distribution optimization' },
              { name: 'component:cdn-integration', color: '0e8a16', description: 'Content delivery network' },
              { name: 'component:resource-optimization', color: '0e8a16', description: 'CPU, memory, and I/O optimization' },
              { name: 'component:performance-testing', color: '0e8a16', description: 'Load and stress testing' },
              { name: 'component:auto-scaling', color: 'c2e0c6', description: 'Automatic horizontal/vertical scaling' },
              { name: 'component:disaster-recovery', color: 'c2e0c6', description: 'Backup and recovery procedures' },
              { name: 'component:failover-systems', color: 'c2e0c6', description: 'Automatic failover mechanisms' },
              { name: 'component:multi-region-deployment', color: 'c2e0c6', description: 'Geographic distribution' },
              { name: 'component:circuit-breakers', color: 'c2e0c6', description: 'Service protection patterns' },
              { name: 'component:health-checks', color: 'c2e0c6', description: 'Service health validation' },
              { name: 'component:audit-trail', color: 'd93f0b', description: 'Comprehensive audit logging' },
              { name: 'component:privacy-management', color: 'd93f0b', description: 'Data privacy and protection' },
              { name: 'component:compliance-automation', color: 'd93f0b', description: 'Automated compliance checking' },
              { name: 'component:policy-enforcement', color: 'd93f0b', description: 'Governance policy automation' },
              { name: 'component:api-gateway', color: '0052cc', description: 'Unified API access point' },
              { name: 'component:service-mesh', color: '0052cc', description: 'Inter-service communication' },
              { name: 'component:api-documentation', color: '0052cc', description: 'Auto-generated API docs' },
              { name: 'component:service-discovery', color: '0052cc', description: 'Dynamic service registration' },
              { name: 'component:cicd-pipeline', color: 'fbca04', description: 'Automated deployment pipeline' },
              { name: 'component:container-orchestration', color: 'c2e0c6', description: 'Docker and Kubernetes' },
              { name: 'component:data-management', color: '1d76db', description: 'Backup and storage systems' },
              { name: 'component:integration-platform', color: 'e99695', description: 'Cross-component integration' },
              { name: 'component:executive-dashboard', color: 'fbca04', description: 'Leadership KPI visualization' },
              { name: 'component:advanced-reporting', color: 'fbca04', description: 'Automated report generation' },
              { name: 'component:ai-ml-engine', color: '0e8a16', description: 'Machine learning capabilities' },
              { name: 'component:federation-support', color: '5319e7', description: 'Multi-organization governance' },
              { name: 'component:equity-ui-v2', color: 'fbca04', description: 'Modern frontend dashboard' },
              { name: 'component:mobile-interface', color: 'fbca04', description: 'Mobile-responsive design' },
              { name: 'component:accessibility-framework', color: 'fbca04', description: 'WCAG compliance implementation' },

              // Team Assignment Labels
              { name: 'team:lead-architect', color: '5319e7', description: 'Lead Infrastructure Architect' },
              { name: 'team:backend-dev', color: '1d76db', description: 'Backend Systems Developer' },
              { name: 'team:devops', color: 'd93f0b', description: 'DevOps Engineer' },
              { name: 'team:security', color: 'b60205', description: 'Security Specialist' },
              { name: 'team:qa', color: '0e8a16', description: 'Quality Assurance Engineer' },
              { name: 'team:frontend-lead', color: 'fbca04', description: 'Frontend Lead' },
              { name: 'team:ux-designer', color: 'fbca04', description: 'UX/UI Designer' },
              { name: 'team:accessibility', color: 'fbca04', description: 'Accessibility Specialist' },
              { name: 'team:data-engineer', color: '0052cc', description: 'Data Engineer' },
              { name: 'team:ml-engineer', color: '0052cc', description: 'ML Engineer' },
              { name: 'team:bi-engineer', color: '0052cc', description: 'Business Intelligence Engineer' },
              { name: 'team:external', color: 'c2e0c6', description: 'External Consultant' },
              { name: 'team:community', color: '0e8a16', description: 'Community Contributor' },
              { name: 'team:unassigned', color: 'ededed', description: 'Not yet assigned' },

              // Health Score Labels
              { name: 'health:100', color: '0e8a16', description: '100/100 - Complete, Production ready' },
              { name: 'health:90-99', color: '0e8a16', description: '90-99/100 - Nearly complete, Minor polish' },
              { name: 'health:75-89', color: '1d76db', description: '75-89/100 - Substantial progress, On track' },
              { name: 'health:50-74', color: 'fbca04', description: '50-74/100 - Moderate progress, Some concerns' },
              { name: 'health:25-49', color: 'd93f0b', description: '25-49/100 - Limited progress, Needs attention' },
              { name: 'health:0-24', color: 'b60205', description: '0-24/100 - Minimal progress, Requires intervention' },

              // Implementation Size Labels  
              { name: 'size:small', color: '0e8a16', description: '< 10KB - Small component or feature' },
              { name: 'size:medium', color: '0e8a16', description: '10-25KB - Medium component' },
              { name: 'size:large', color: '1d76db', description: '25-50KB - Large component' },
              { name: 'size:very-large', color: 'fbca04', description: '50-100KB - Very large component' },
              { name: 'size:enterprise', color: 'd93f0b', description: '100KB+ - Major infrastructure component' },
              { name: 'size:system', color: 'b60205', description: 'Enterprise Scale - Multi-component system' },

              // Iteration Labels for Agile Planning
              { name: 'iteration:sprint-1', color: '1d76db', description: 'Sprint 1 - Week 1-2 iteration' },
              { name: 'iteration:sprint-2', color: '1d76db', description: 'Sprint 2 - Week 3-4 iteration' },
              { name: 'iteration:sprint-3', color: '1d76db', description: 'Sprint 3 - Week 5-6 iteration' },
              { name: 'iteration:sprint-4', color: '1d76db', description: 'Sprint 4 - Week 7-8 iteration' },
              { name: 'iteration:sprint-5', color: '1d76db', description: 'Sprint 5 - Week 9-10 iteration' },
              { name: 'iteration:sprint-6', color: '1d76db', description: 'Sprint 6 - Week 11-12 iteration' },
              { name: 'iteration:epic', color: '5319e7', description: 'Epic - Multi-sprint epic work' },
              { name: 'iteration:maintenance', color: 'c2e0c6', description: 'Maintenance - Ongoing maintenance work' },
              { name: 'iteration:research', color: 'd93f0b', description: 'Research - Research and discovery phase' },

              // Risk labels
              { name: 'risk:low', color: '0e8a16', description: 'Low risk' },
              { name: 'risk:medium', color: 'fbca04', description: 'Medium risk' },
              { name: 'risk:high', color: 'd93f0b', description: 'High risk' },

              // Status labels
              { name: 'status:todo', color: 'ededed', description: 'To Do' },
              { name: 'status:in-progress', color: '0e8a16', description: 'In Progress' },
              { name: 'status:in-review', color: 'fbca04', description: 'In Review' },
              { name: 'status:blocked', color: 'd93f0b', description: 'Blocked' },
              { name: 'status:done', color: '1d76db', description: 'Done' },
              { name: 'status:testing', color: '5319e7', description: 'Testing phase' },
              { name: 'status:deployed', color: '0052cc', description: 'Deployed to production' },

              // Helper labels for date parsing (examples)
              { name: 'start:2025-01-28', color: 'c5def5', description: 'Start date example - use start:YYYY-MM-DD format' },
              { name: 'due:2025-02-04', color: 'c5def5', description: 'Due date example - use due:YYYY-MM-DD format' },

              // Helper labels for estimate parsing (examples)  
              { name: 'est:h:8', color: 'c5def5', description: 'Estimate example - use est:h:XX format' },
              { name: 'est:h:16', color: 'c5def5', description: 'Estimate example - use est:h:XX format' },
              { name: 'est:h:40', color: 'c5def5', description: 'Estimate example - use est:h:XX format' },
              { name: 'est:h:80', color: 'c5def5', description: 'Estimate example - use est:h:XX format' },

              // Additional helper labels for better workflow triggers
              { name: 'in-progress', color: '0e8a16', description: 'Legacy in-progress label (auto-maps to Status)' },
            ];

            async function upsert(label) {
              try {
                // Try update first
                await github.rest.issues.updateLabel({ owner, repo, name: label.name, new_name: label.name, color: label.color, description: label.description || '' });
                console.log('Updated label:', label.name);
              } catch (e) {
                if (e.status === 404) {
                  await github.rest.issues.createLabel({ owner, repo, name: label.name, color: label.color, description: label.description || '' });
                  console.log('Created label:', label.name);
                } else {
                  throw e;
                }
              }
            }
            for (const l of labels) { await upsert(l); }
            console.log('Labels seeded/updated.');