name: "Semgrep"
on:
  pull_request:
  push:
    
    param($m)
    $inside = $m.Groups[1].Value + 'main' + $m.Groups[2].Value
    if ($inside -notmatch 'master') { return 'branches: [' + ($inside.Trim().TrimEnd(',')) + ', master]' }
    return $m.Value
  
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: read
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: >-
            p/ci
          generateSarif: true
          output: semgrep-results.sarif.json
      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Enforce Semgrep policy
        run: node tools/enforce-semgrep.js
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: always()
        with:
          name: semgrep-artifacts
          path: |
            semgrep-results.sarif.json
            artifacts/sast-semgrep-enforce-summary.json